cbsd/cbsd

- sudoexec/initenv
Fixed some problems with English which I noticed during initial installation.
> Insignificant message text fixes

- Makefile
- bin/cfetch.c
- etc/defaults/vm-freebsd-FreeBSD-x64-12.0-LATEST.conf
- etc/defaults/vm-linux-CentOS-7-x86_64.conf
- etc/defaults/vm-linux-fedora-server-26-x86_64.conf
- initenv.subr
- settings-tui.subr
- sudoexec/initenv
- system/buildworld
- system/preparebase
- tools/help
- tools/makejconf
- virtual.subr
Fixes for grep error on initial setup.  Issue #176, Thanks to Vladislav V. Prodan aka click0;
Correct text on initenv stage to avoid confusing the user with the version mismatch. Issue #177, Thanks to Vladislav V. Prodan aka click0;
> Automatic selection of a suitable mirror when downloading images;

- sudoexec/jstart
> only warning with vnet=1 on non-VNET hoster

- HardenedBSD.subr
- Makefile
- sudoexec/initenv
- tools/repo
AllBSD prooved to be more stable mirror, hence the change there
> Fix HardenedBSD support

- bhyve.subr
- jailctl/jexport
- share/bsdconfig/cbsd/bhyvedsk-cfgdsk
- share/bsdconfig/cbsd/xendsk-cfgdsk
- tools/bhyvedsk
- tools/bhyvenic
- tools/imgremove
- tools/media
- tools/xendsk
- virtual.subr
- virtualbox.subr
- xen.subr
+ jexport: add genmd5 gensize args
> fix size column in "cbsd bhyvedsk" and "cbsd media"

- etc/defaults/bhyve-default-default.conf
- etc/defaults/virtualbox-default-default.conf
- etc/defaults/vm-linux-Debian-x86-9.conf
- etc/defaults/xen-default-default.conf
- jailctl/jexport
- settings-tui.subr
- sudoexec/bstart
- virtual.subr
> bstart/vm_cpus: warning when vcpus onvercommited

- etc/defaults/vm-freebsd-HardenedBSD-x64-11-stable.conf
@mekanix HardenedBSD 11-1100055. Time to ASLR jail ?
> HardenedBSD 11-1100055

- bhyve.subr
This is just a POC so we can discuss the idea(s). I put config into rc.conf only because it was convenient to  test, so what would be the proper way to implement this idea?
closes #270
> Make autoconnection of bridge togglable

- Makefile
- bhyve.subr
Works for me. I don't know what other test to execute except "run vm and it works".
> Use sparse ZVOLs

- sudoexec/bremove
> Remove snapshots of bclone

- misc/src/dump_cpu_topology.c
Without it displays 0 cores, not the best way to do it but tested it to work with a few different xml outputs.
> Fix for CPU's without HT

- rc.d/cbsdd
> Problem with cbsdd status pid

- tools/imgpart
> Add block size for dd command on image export

- jailctl/bscp
- jailctl/jscp
- modules/bsdconf.d/adduser-tui
- nc.subr
- settings-tui.subr
- sudoexec/jlogin
- tools/jconstruct
btw always quote its arg when calling it.
grep regexp changed: remove useless escaping, add ";" as forbidden char and remove "E" as forbidden char.
> fix validate_jname function and reverse its return value

- jailctl/bget
- share/bhyve.conf
This makes bget a lot handier. This way you don't have to know it all by default.
Also displays all by default as well unless told what to show.
> add a all option to bget

- modules/pkg.d/pkg.subr
> Fix minor typo

- share/autocompletion/bash/CBSDCompletion.bash
Added Bash autocompletion file for most common used commands
> Added Bash autocompletion file for most common used commands

- share/autocompletion/bash/CBSDCompletion.bash
Fixed bconfig autocompletion bug and added bremove/jremove command autocompletions
> Fixed bconfig autocompletion bug and added bremove/jremove command autocompletions

- jailctl/vcreate
- jailctl/vls
- jailctl/vsetup-tui
- jailctl/vstart
- jailctl/vstop
- jailctl/xcreate
- jailctl/xset
- modules/bsdconf.d/adduser-tui
- sudoexec/xstop
- tools/bhyve-nic-list
- tools/bhyve-nic-tui
There are some typos or copy/paste forgotten in some MYDESC. 
Here are the ones I propose to modify.
> Fix some MYDESC descriptions

- release/install.sh
- upgrade/post-patch-11.0.0.0
- upgrade/post-patch-11.0.16.0
- upgrade/post-patch-11.0.3.0
- upgrade/post-patch-11.0.5.0
- upgrade/post-patch-11.0.6.0
- upgrade/post-patch-11.1.17.0
- upgrade/post-patch-11.1.3.0
fixd upgrade post-patches and release/install.sh
> move subroutines to ./subr - part 2
