- tools/jconstruct
The correct message for NIC input in jconstruct should be used, not the IP address/mask message, as it is confusing.
> Use the correct message for NIC input in jconstruct.

- etc/defaults/vm-linux-ubuntuserver-x86-14.04.conf
vm_profile did not match the filename, causing Ubuntu 14.04 LTS bconstruct to fail with `No such profile: vm-linux-ubuntuserver-x86-14.04.4.conf`
> Fix vm_profile name to match filename

- tools/expose
I wrapped the line that checks if net.inet.ip.fw.enable is set in an if that just checks if cbsd is set up to use ipfw. Because if its not then that check won't pass at all since net.inet.ip.fw doesn't exist. 
This allows pf users to use expose without having to enable ipfw
> Fix cbsd expose not working without ipfw enabled

- jcreate.subr
We dont need to restore PATH here due to cbsd shell will override it anyway.
We need to overwrite PATH only for master hook execution, not for jexec.  Issue #197
> rollback for /usr/local/bin/cbsd before jexec

- jailctl/jcreate
As `temprcconf` is generated with user running jcreate, original `jconf` perms are overwritten by cp
> Preserve jconf perms

- sudoexec/initenv
- tools/makeresolv
initenv: support for pre-defined config for re-configure
makeresolv now support optional args:
cbsd makeresolv file=<path-to-resolv.conf>
cbsd makeresolv nameserver=8.8.8.8
cbsd makeresolv nameserver=8.8.4.4,8.8.8.8
for independent configuration of jails /etc/resolv.conf
initenv: fast hack to support pre-defined variables from config file for re-configure, e.g:
cat > /tmp/initenv.conf << EOF
jnameserver="8.8.8.8,8.8.4.4"
nodeip="192.168.0.1"
EOF
cbsd initenv inter=0 /tmp/initenv.conf
> makeresolv: add optional nameserver and path args for independency

- tools/attachzfs
We do not need to return upon fstab processing if we encounter a bad record.
Just keep going.
Reported and fix suggestion by: uropro , via Issue #241
> attachzfs fixes for mount points > 1

- jailctl/jsetup-tui
"b_order" now is simple "order". Reported and pointed out by: Andrii Mazan aka Fazik
Issue #244
> fixed the legacy of the old code

- etc/defaults/vm-freebsd-FreeBSD-x64-12.0-LATEST.conf
- initenv.subr
- jailctl/jsetup-tui
- settings-tui.subr
- share/initenv.conf
- tools/bconstruct-tui
- tools/jconstruct-tui
when /usr/local/cbsd/sudoexec/initenv inter=0 <path_file> used, skip read on
NAT framework choosing when non-interactive flags used
* [jb]consturct-tui: store previous profile choices
> * fix for inter=0 at nat framework question

- bin/cbsdsh/about.h
- cbsd.conf
- cbsd.lua
- jailctl/jexport
- jailctl/jimport
- tools/imgpart
- tools/imgremove
- tools/src/imghelper.c
* jexport: add dstdir
alternative directory for saving images;
* jexport: support for wss notification for ClonOS
* added tools/imgremove: script for safe removal CBSD images:
- we check that the file is an image of CBSD before deleting.
This script is mainly used by the ClonOS because it does not
have the right to delete files.
* imghelper.c micro optimization: we search for the header only in
the first 1MB. If header signature is not detected - error 1.
This speeds up the validation of large files that are not CBSD images
> impove jexport part

- virtual.subr
Now we not only find the winner and use it as first mirror,
but also sort the subsequent mirrors as they deteriorate
> fetch_iso: sort mirror by fastest resource

- tools/baseupdate
freebsd-update install fails if there's nothing to install, so `cbsd baseupdate` was always exiting with error if there's no update. This way, freebsd-update is smart enough to not run install if fetch didn't get new patches.
> Let freebsd-update determine if install is needed

- jailctl/jrctl
Последняя версия  Prometheus 2.4.3 выводит ошибку: `expected value after metric, got "MNAME"` - это происходит из-за того, что некоторые значения не отдаются rctl и парсинге index.html выводится ошибка и данные не складываются
До патча:
```
bhyve_test_datasize 2125824
bhyve_test_stacksize 0
bhyve_test_coredumpsize 0
bhyve_test_memoryuse 236089344
bhyve_test_memorylocked 0
bhyve_test_maxproc 1
bhyve_test_openfiles 0
bhyve_test_vmemoryuse 1149112320
bhyve_test_pseudoterminals 
bhyve_test_swapuse 
bhyve_test_nthr 21
bhyve_test_msgqqueued 
bhyve_test_msgqsize 
bhyve_test_nmsgq 
bhyve_test_nsem 
bhyve_test_nsemop 0
bhyve_test_nshm 
bhyve_test_shmsize 
bhyve_test_wallclock 2135
bhyve_test_pcpu 0
bhyve_test_readbps 0
bhyve_test_writebps 0
bhyve_test_readiops 0
bhyve_test_writeiops 0
```
После: …
> Define value by 0 if rctl dont have any data

- bhyve.subr
Solves the problem if already configured device is renamed. Example: `ifconfig_bridge0_name="cbsd"`
> Search for bridge by group

- etc/defaults/vm-openbsd-x86-6.conf
Update vm-openbsd-x86-6.conf
Fix a typo on iso_img:
- install63.fs -> install64.fs
> Fix typo in vm-openbsd-x86-6.conf (64 vs 63)

- modules/bsdconf.d/adduser
Functionality for setting UID and GID when creating a user in a jail is already there in the adduser script. However it didn't offer it at jail creation when reading parameters from a jconf file. This commit adds the missing functionality.
Limitation: The corresponding lines (i.e. "user_uid_$NAME" and "user_gid_$NAME") have to be added by hand / configuration management at this point. The script adduser-tui was not extended to offer dialogs for setting them.
> Enable adduser script to honor UID and GID when present in jconf file

- jailctl/j2slave
- sudoexec/initenv
- sudoexec/jstart
- tools/fwcounters
Makes using master_poststartup.d for automatic ipfw add ... jail ${jid} possible
Also deletes all rules with "jail ${jid}" when the jail gets removes
Fixed loop in initenv-tui with a not FQDN as hostname
Fixed verbose rsync
> Few improvements

- bhyve.subr
- jailctl/blogin
- sudoexec/bstart
- sudoexec/bstop
Old behavior cbsd not work inside tmux session, with error
"sessions should be nested with care, unset $TMUX to force"
Now bhyve instance make dedicated tmux socket/server.
Default control in nested session, prefix key 'Ctrl+b+b'
Deleted attach `cbsdb-${jname}` exist only in blogin
live migration not tested.
> Add tmux nested mode for bhyve.

- vnet.subr
As `get_my_device()` is called with `bridge` or `epair` as first argument, which are also interface group names, `ifconfig -g bridge` can be used. It fixes a bug on systems where bridge interface for CBSD is already configured but it's name is changed like so:
```
ifconfig_bridge0_name="cbsd0"
ifconfig_cbsd0="inet 172.16.0.254 netmask 255.255.255.0 description lagg0"
```
> Search bridge/epair by group name

- settings-tui-virtual.subr
- sudoexec/bstart
- sudoexec/xstart
Changes to enable that vm_cpus_max is used throughout the code instead of the hardcoded value of 16. 
I have tested it on FreeBSD 12.1 and it worked for me.
> Replaced hardcoded max. for vm_cpus

- jailctl/jrctl
This PR adds the jail/vm name as label rather than having it as part of the metric name. I believe this follows the idea of how metrics should be named and labeled in Prometheus a bit closer than now.
> added label 'name' for prometheus metrics

- sudoexec/jstop
- tools/makejconf
Do not exclude bridge interface on jstop. (also effects tools/makejconf)
fixed a missing comment in the jstop script.
> fixed jstop script to work correctly with jails on bridges

- jailctl/emulator
Use case is simple: Should scripts (external to CBSD) run `bstart` or `jstart` if only data they have is the name?
> Add command to print emulator of an instance

- sudoexec/bcreate
Fixes https://github.com/cbsd/cbsd/issues/609
> bcreate: do not remove jconf by default
